name: "MyPodcastGenerator"
author: "Titilope-Orukotan"
description: "Generate a podcast episode from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "red"
  icon: "git-branch"
inputs:
  email: 
    description: "Email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The commiter's name"
    required: true
    default: ${{ github.actor }}
